version: "3.8"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgresql14-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  postgres_test:
    image: postgres:14
    command: -c max_connections=300
    ports:
      - "5433:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgresql14-data:

networks:
  default:
    attachable: true
